### ISSUE TITLE
crawling monitor performance

### ISSUE THREAD

**Issue by MortenHofft** [gbif/management-tools#13]
I find the new crawling monitor to be markedly slower than the existing ones. Is that what you are seeing as well @timrobertson100 ? 

Perhaps adding occurrence counts and dataset titles didn't do anything good for performance. Or angular just isn't good with large tables (which is a known problem)

**Comment by MattBlissett** [comment]
It's slow now that there are 190 entries in the table.

I think it's worth keeping the counts and titles, they're worth a slowdown. Maybe limit the displayed part of the table to 50 entries or so?

But the refresh is slow because retrieving the status for 190 rows takes about a second. The old monitor would retrieve the status only for the selected entries, which at a time like today is probably one or two entries. These are 60ms each.

**Comment by MortenHofft** [comment]
refreshing every few seconds is okay isn't it? Or do you need it to be faster than that? If so i should do it per row as in the old one. it was just simpler to do the whole lot instead. 

I don't know how much of a difference it makes so limit rows as they are all loaded anyhow. But some effect it will have. I can add that option. And then there is the option to select the rows you are interested in and click `Only show selected` 

I'll try limiting default page size

**Comment by MortenHofft** [comment]
I've added page size and throttled lookups - at least it helped. Let me know if you believe this is something i should look more into
